clone:
  git:
    image: plugins/git
    recursive: false

pipeline:
  build:
    image: prima/drone-tools:1.14.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/cache/ci/${DRONE_REPO}/${DRONE_BRANCH}:/var/cache/ci
      - /etc/profile.d/ecs-credentials-endpoint:/etc/profile.d/ecs-credentials-endpoint
    commands:
      - . /etc/profile.d/ecs-credentials-endpoint
      - prepare-docker-compose
      - cache-restore --docker-cache-pull --no-files
      - docker-compose build
      - docker-compose run -w $PWD web "yarn install"
      - docker-compose run -w $PWD web "yarn build:site"
      - docker-compose run -w $PWD web "yarn build:css"
      - if [ -n "${DRONE_TAG}" ]; then ./deploy/deploy production ${DRONE_TAG}; elif [ "${DRONE_BRANCH}" = "master" ]; then ./deploy/deploy staging; fi
      - cache-save ~/.node-modules ~/.elm-stuff

  notify_email:
    image: drillster/drone-email
    host: email-smtp.eu-west-1.amazonaws.com
    secrets: [ email_username, email_password ]
    from: noreply@prima.it
    when:
      status: [ changed, failure ]

  cleanup:
    image: prima/drone-tools:1.14.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - teardown
    when:
      status: [ success, killed, failure ]
