---
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Environment:
    Type: String
    AllowedValues:
      - staging
      - production
      - qa
  ECSClusterName:
    Type: String
    Default: ''      
  ReleaseVersion:
    Type: String
  TaskDesiredCount:
    Type: Number
    Default: 2
  ALBShortName:
    Type: String
    Default: ""
  EnvHash:
    Type: String
    Default: ""    
  HostnamePattern:
    Type: String
  HostnamePatternPriority:
    Type: Number
    Default: 1

Mappings:
  ECSCluster:
    qa:
      id: ""
      MixEnv: qa
      PyxisCpu: 32
      PyxisRam: 32
      MinServiceSize: 1
      MaxServiceSize: 1
      PyxisHostname: ""
      HealthyThreshold: 10
      DeploymentMaximumPercent: 100
      DeploymentMinimumHealthyPercent: 0
      ALBShortName: ""
      HealthCheckGracePeriodSeconds: 120
      DnsServers:
        - "172.17.0.1"
        - "10.43.0.2"    
    staging:
      id: ecs-cluster-allinone-staging-ECSCluster-1ECKQ785CYFWL
      PyxisCpu: 32
      PyxisRam: 32
      MinServiceSize: 2
      MaxServiceSize: 2
      HealthyThreshold: 10
      DeploymentMaximumPercent: 100
      DeploymentMinimumHealthyPercent: 50
      ALBShortName: pyxis-staging
    production:
      id: ecs-cluster-as-microservices-vpc-production-ECSCluster-NBrZ5IigmJnV
      PyxisCpu: 128
      PyxisRam: 128
      MinServiceSize: 2
      MaxServiceSize: 5
      HealthyThreshold: 10
      DeploymentMaximumPercent: 100
      DeploymentMinimumHealthyPercent: 50
      ALBShortName: pyxis-production

Conditions:
  IsQA: !Equals [!Ref Environment, qa]
  IsNotQA: !Not [!Equals [!Ref Environment, qa]]
  TaskDesiredCountZero: !Equals [!Ref TaskDesiredCount, 0]

Resources:
  ECSServicePyxis:
    Type: AWS::ECS::Service
    Condition: IsNotQA
    Properties:
      Cluster: !FindInMap [ECSCluster, !Ref Environment, id]
      PlacementStrategies:
        - Field: attribute:ecs.availability-zone
          Type: spread
        - Field: instanceId
          Type: spread
      LaunchType: EC2
      SchedulingStrategy: REPLICA
      DesiredCount:
        !If [TaskDesiredCountZero, !Ref "AWS::NoValue", !Ref TaskDesiredCount]
      TaskDefinition:
        Ref: TaskDefinitionPyxis
      LoadBalancers:
        - ContainerName: pyxis
          ContainerPort: 80
          TargetGroupArn:
            Ref: ApplicationLoadBalancerTargetGroup
      DeploymentConfiguration:
        MaximumPercent:
          Fn::FindInMap:
            - ECSCluster
            - Ref: Environment
            - DeploymentMaximumPercent
        MinimumHealthyPercent:
          Fn::FindInMap:
            - ECSCluster
            - Ref: Environment
            - DeploymentMinimumHealthyPercent
      Role:
        Fn::ImportValue:
          Fn::Sub: ecs-roles-pyxis-${Environment}-service
    DependsOn:
      - ApplicationLoadBalancerHttpsListenerRule

  ECSServicePyxisAutoscalingCpu:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Condition: IsNotQA
    Properties:
      PolicyName: !Sub pyxis-application-autoscaling-cpu-${Environment}
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ECSServicePyxisScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 75.0
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        ScaleOutCooldown: 150
        ScaleInCooldown: 300

  ECSServicePyxisAutoscalingMemory:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Condition: IsNotQA
    Properties:
      PolicyName: !Sub pyxis-application-autoscaling-memory-${Environment}
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ECSServicePyxisScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 75.0
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageMemoryUtilization
        ScaleOutCooldown: 150
        ScaleInCooldown: 300

  ECSServicePyxisScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Condition: IsNotQA
    Properties:
      MaxCapacity: !FindInMap [ECSCluster, !Ref Environment, MaxServiceSize]
      MinCapacity: !FindInMap [ECSCluster, !Ref Environment, MinServiceSize]
      ResourceId: !Sub
        - service/${ClusterName}/${ECSServicePyxis.Name}
        - { ClusterName: !FindInMap [ECSCluster, !Ref Environment, id] }
      RoleARN: arn:aws:iam::001575623345:role/ecsAutoscaleRole
      ServiceNamespace: ecs
      ScalableDimension: ecs:service:DesiredCount
    DependsOn: ECSServicePyxis

  TaskDefinitionPyxis:
    Type: AWS::ECS::TaskDefinition
    Properties:
      TaskRoleArn:
        Fn::ImportValue:
          Fn::Sub: ecs-roles-pyxis-${Environment}-task
      ContainerDefinitions:
        - Name: pyxis
          Image: 595659439703.dkr.ecr.eu-west-1.amazonaws.com/pyxis:1.12.2-2
          Essential: true
          Cpu: !FindInMap [ECSCluster, !Ref Environment, PyxisCpu]
          MemoryReservation: !FindInMap [ECSCluster, !Ref Environment, PyxisRam]
          PortMappings:
            - HostPort: !If [IsQA, 15990, 0]
              ContainerPort: 80
          Environment:
            - Name: AWS_STACK_NAME
              Value:
                Ref: AWS::StackName
            - Name: VERSION
              Value:
                Ref: ReleaseVersion
            - Name: ENV
              Value: !Ref Environment
            - Name: PORT
              Value: "80"
      Volumes:
        - Name: awseb-logs-system
          Host:
            SourcePath: "/var/log"

  ApplicationLoadBalancerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Condition: IsNotQA
    Properties:
      HealthCheckIntervalSeconds: 5
      HealthCheckPath: "/health-check"
      HealthCheckPort: traffic-port
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 4
      HealthyThresholdCount:
        Fn::FindInMap:
          - ECSCluster
          - Ref: Environment
          - HealthyThreshold
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: "200"
      Port: 80
      Protocol: HTTP
      Name: !FindInMap [ECSCluster, !Ref Environment, ALBShortName]
      Tags:
        - Key: Name
          Value:
            Ref: AWS::StackName
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: "30"
        - Key: stickiness.enabled
          Value: "true"
        - Key: stickiness.type
          Value: lb_cookie
        - Key: stickiness.lb_cookie.duration_seconds
          Value: "360"
      VpcId:
        Fn::ImportValue: !Sub Vpc-${Environment}

  ApplicationLoadBalancerHttpsListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Condition: IsNotQA
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn:
            Ref: ApplicationLoadBalancerTargetGroup
      Conditions:
        - Field: host-header
          Values:
            - !Ref HostnamePattern
      ListenerArn:
        Fn::ImportValue: !Sub ALBPublicDefaultHttpsListener-http-${Environment}
      Priority: !Ref HostnamePatternPriority




  ECSServicePyxisQA:
    Type: AWS::ECS::Service
    Condition: IsQA
    Properties:
      Cluster: !Ref ECSClusterName
      SchedulingStrategy: REPLICA
      DesiredCount: !Ref TaskDesiredCount
      TaskDefinition:
        Ref: TaskDefinitionPyxis
      LoadBalancers:
        - ContainerName: Pyxis
          ContainerPort: 80
          TargetGroupArn:
            Ref: ApplicationLoadBalancerTargetGroupPublic
      DeploymentConfiguration:
        MaximumPercent:
          !FindInMap [ECSCluster, !Ref Environment, DeploymentMaximumPercent]
        MinimumHealthyPercent:
          !FindInMap [
            ECSCluster,
            !Ref Environment,
            DeploymentMinimumHealthyPercent,
          ]
      Role:
        Fn::ImportValue: !Sub ecs-roles-Pyxis-${Environment}-service
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
        - Key: prima:country
          Value: IT
        - Key: prima:environment
          Value: !Ref Environment
        - Key: prima:application-name
          Value: Pyxis
        - Key: prima:cluster-role
          Value: allinone
    DependsOn:
      - ApplicationLoadBalancerHttpsListenerRuleQA

  ApplicationLoadBalancerTargetGroupPublic:
      Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Condition: IsQA
      Properties:
        HealthCheckIntervalSeconds: 10
        HealthCheckPath: "/health-check"
        HealthCheckPort: traffic-port
        HealthCheckProtocol: HTTP
        HealthCheckTimeoutSeconds: 9
        HealthyThresholdCount:
          !FindInMap [ECSCluster, !Ref Environment, HealthyThreshold]
        UnhealthyThresholdCount: 5
        Matcher:
          HttpCode: "200"
        Port: 80
        Protocol: HTTP          
        Name:
          Fn::Join:
            - ""
            - - Fn::FindInMap:
                  - ECSCluster
                  - Ref: Environment
                  - ALBShortName
              - Ref: ALBShortName
        Tags:
          - Key: prima:country
            Value: IT
          - Key: prima:environment
            Value: !Ref Environment
          - Key: prima:application-name
            Value: pyxis
          - Key: Name
            Value:
              Ref: AWS::StackName
        TargetGroupAttributes:
          - Key: deregistration_delay.timeout_seconds
            Value: "30"
          - Key: stickiness.enabled
            Value: "false"
        VpcId:
          Fn::ImportValue: !Sub Vpc-${Environment}

  ApplicationLoadBalancerHttpsListenerRuleQA:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Condition: IsQA
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn:
            Ref: ApplicationLoadBalancerTargetGroupPublic
      Conditions:
        - Field: host-header
          Values:
            - !Ref HostnamePattern
      ListenerArn:
        Fn::ImportValue: !Sub ALBPublicDefaultHttpsListener-http-${Environment}${EnvHash}
      Priority: !Ref HostnamePatternPriority          